name: AI Code Review

on:
  pull_request:
    branches: ['main', 'dev']

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: AI Code Review Action
        uses: villesau/ai-codereviewer@v2.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
